### ISSUE TITLE
Project Banner not showing

### ISSUE THREAD

**Issue by imalisiddique** [elis/project-banner#1]
https://www.dropbox.com/s/1tpeh02tui2zmfp/pb.jpg?dl=0

**Comment by elis** [comment]
- Make sure you activate the plugin (CTRL+SHIFT+P -> `Project Banner: Toggle`)
- Make sure that your `package.json` and/or `.bannerfile.json` are proper json - it sometimes fails if the `json` files aren't properly formatted

**Comment by imalisiddique** [comment]
It's working now. Thanks for reply.
